{% set name = "fitsio" %}
{% set version = "1.0.1" %}
{% set sha256 = "6bdecabb122c04eaef57e9d556a4034d6a0e5b4fa585590d3d28e05a6c11de14" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # fn: {{ name }}-{{ version }}.tar.gz
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # sha256: {{ sha256 }}
  git_url: https://github.com/esheldon/fitsio.git
  git_rev: windows

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - make                 # [not win]
    - m2w64-toolchain      # [win]
    - m2-git               # [win]
    - posix                # [win]
  host:
    - python
    - pip
    - numpy
    - bzip2
    - libcurl
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - bzip2
    - m2w64-gcc-libs       # [win]

test:
  imports:
    - fitsio
  commands:
    - python -c "import fitsio; fitsio.test.test()"

about:
  home: https://github.com/esheldon/fitsio
  license: GPL
  license_file: LICENSE.txt
  summary: A python library to read from and write to FITS files.
  description: |
    This is a python extension written in c and python. Data are read into
    numerical python arrays. A version of cfitsio is bundled with this package,
    there is no need to install your own, nor will this conflict with a
    version you have installed.
  doc_url: https://github.com/esheldon/fitsio
  dev_url: https://github.com/esheldon/fitsio

extra:
  recipe-maintainers:
    - beckermr
