{% set name = "fitsio" %}
{% set version = "1.2.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/esheldon/fitsio/archive/refs/tags/{{ version }}.tar.gz
  sha256: e6009326686d6e5ceb68208cfc9b79f579315baba760fd9cc9d703ae5e42de5e
  patches:
    - 0001-array-api.patch  # [version == "1.2.6"]

build:
  number: 1
  skip: true  # [win]
  # zlib is bundled
  # we put it in host to make configure happy
  ignore_run_exports_from:
    - zlib

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - libtool  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make
  host:
    - python
    - pip
    - setuptools
    - numpy
    - bzip2
    - libcurl
    - zlib
  run:
    - python
    - bzip2
    - setuptools  # the test modules now use pkg_resources

test:
  requires:
    - pytest
  imports:
    - fitsio
  commands:
    - pytest --pyargs fitsio.tests

about:
  home: https://github.com/esheldon/fitsio
  license: GPL-2.0-only AND Zlib
  license_file:
    - LICENSE.txt
    - LICENSE_cfitsio.txt
    - LICENSE_zlib.txt
  summary: A python library to read from and write to FITS files.
  description: |
    This is a python extension written in c and python. Data are read into
    numerical python arrays. A version of cfitsio is bundled with this package,
    there is no need to install your own, nor will this conflict with a
    version you have installed.
  doc_url: https://github.com/esheldon/fitsio
  dev_url: https://github.com/esheldon/fitsio

extra:
  recipe-maintainers:
    - beckermr
