{% set name = "fitsio" %}
{% set version = "1.1.3" %}
{% set sha256 = "abed9700a1aaada9a74315b17bd0b14f4c08603a35783fc51a12e02c0e33b797" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - bzip2
    - libcurl

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - bzip2
    - setuptools  # the test modules now use pkg_resources

test:
  imports:
    - fitsio
  commands:
    - python -c "import fitsio; fitsio.test.test()"

about:
  home: https://github.com/esheldon/fitsio
  license: GPL-2.0-only
  license_file: LICENSE.txt
  summary: A python library to read from and write to FITS files.
  description: |
    This is a python extension written in c and python. Data are read into
    numerical python arrays. A version of cfitsio is bundled with this package,
    there is no need to install your own, nor will this conflict with a
    version you have installed.
  doc_url: https://github.com/esheldon/fitsio
  dev_url: https://github.com/esheldon/fitsio

extra:
  recipe-maintainers:
    - beckermr
