{% set name = "fitsio" %}
{% set version = "1.2.1" %}
{% set sha256 = "c64f60588f25fb2ba499854082bca73b0eda43b32ed6091f09dfcbcb72a911a6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  # zlib is bundled
  # we put it in host to make configure happy
  ignore_run_exports_from:
    - zlib

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - libtool  # [unix]
    - {{ compiler('c') }}
    - make
  host:
    - python
    - pip
    - numpy
    - bzip2
    - libcurl
    - zlib
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - bzip2
    - setuptools  # the test modules now use pkg_resources

test:
  requires:
    - pytest
  imports:
    - fitsio
  commands:
    - pytest --pyargs fitsio.tests

about:
  home: https://github.com/esheldon/fitsio
  license: GPL-2.0-only AND Zlib
  license_file:
    - LICENSE.txt
    - LICENSE_cfitsio.txt
    - LICENSE_zlib.txt
  summary: A python library to read from and write to FITS files.
  description: |
    This is a python extension written in c and python. Data are read into
    numerical python arrays. A version of cfitsio is bundled with this package,
    there is no need to install your own, nor will this conflict with a
    version you have installed.
  doc_url: https://github.com/esheldon/fitsio
  dev_url: https://github.com/esheldon/fitsio

extra:
  recipe-maintainers:
    - beckermr
