context:
  name: "fitsio"
  version: "1.4.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/esheldon/fitsio/archive/refs/tags/${{ version }}.tar.gz
  sha256: 7ece7c8234058b5a2c97f7b1259ff396f2d1e91e1cb263ceebd16dde63ab1b9f

build:
  number: 1
  skip:
    - win

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - libtool
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - make
  host:
    - python
    - pip
    - setuptools
    - setuptools-scm
    - numpy
    - bzip2
    - libcurl
    - zlib
  run:
    - python
    - bzip2
    - setuptools  # the test modules now use pkg_resources

  # zlib is bundled
  # we put it in host to make configure happy
  ignore_run_exports:
    from_package:
      - zlib

tests:
  - script:
      - pytest --pyargs fitsio.tests
    requirements:
      run:
        - pytest
        - pytest-run-parallel
        - pytest-skip-slow
  - python:
      imports:
        - fitsio

about:
  homepage: https://github.com/esheldon/fitsio
  license: GPL-2.0-only AND Zlib
  license_file:
    - LICENSE.txt
    - LICENSE_cfitsio.txt
    - LICENSE_zlib.txt
  summary: A python library to read from and write to FITS files.
  description: |
    This is a python extension written in c and python. Data are read into
    numerical python arrays. A version of cfitsio is bundled with this package,
    there is no need to install your own, nor will this conflict with a
    version you have installed.

extra:
  recipe-maintainers:
    - beckermr
