context:
  name: "fitsio"
  version: "1.4.2"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/esheldon/fitsio/archive/refs/tags/${{ version }}.tar.gz
  sha256: 3c786902958e3d130d49300f1ac61071e0e66fe1aba91cf19134369efde3c50c

build:
  number: 0

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: unix
      then:
        - make
      else:
        - cmake <4
        - ninja
        - ${{ compiler("cxx") }}  # CMake needs this, but CFITSIO itself does not
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - setuptools-scm
    - numpy
    - if: unix
      then: bzip2
    - libcurl
  run:
    - python

  # zlib is bundled, but is needed for configure / cmake
  # we put it in host to make configure / cmake happy
  ignore_run_exports:
    from_package:
      - if: win
        then: ${{ compiler("cxx") }}  # CMake needs this, but CFITSIO itself does not          

tests:
  - script:
      - pytest --pyargs fitsio.tests
      - if: unix
        then:
          - python -c "import fitsio; assert fitsio.cfitsio_has_bzip2_support()"
          - python -c "import fitsio; assert fitsio.cfitsio_is_reentrant()"
        else:
          - python -c "import fitsio; assert not fitsio.cfitsio_has_bzip2_support()"
          - python -c "import fitsio; assert not fitsio.cfitsio_is_reentrant()"
      - python -c "import fitsio; assert fitsio.cfitsio_has_curl_support()"
    requirements:
      run:
        - pytest
        - pytest-run-parallel
        - pytest-skip-slow
  - python:
      imports:
        - fitsio

about:
  homepage: https://github.com/esheldon/fitsio
  license: GPL-2.0-only AND Zlib
  license_file:
    - LICENSE.txt
    - LICENSE_cfitsio.txt
    - LICENSE_zlib.txt
  summary: A python library to read from and write to FITS files.
  description: |
    This is a python extension written in c and python. Data are read into
    numerical python arrays. A version of cfitsio is bundled with this package,
    there is no need to install your own, nor will this conflict with a
    version you have installed.

extra:
  recipe-maintainers:
    - beckermr
