travis:
  secure:
    BINSTAR_TOKEN: NcF3DO90b1UkYy6K5hHMHUdZaH3z2ejEm8m+xMrZgGNiNq8FeC8WZHCv54PP1/Lct4E5MM+QZZCHoWkPRX7hq5LYJ1YLMtouoX6/EXGwnqYFbX2vqpf63QC0+5kJqJnJRi/A/2KI/TNSHyOtnjAdrkveRQ1si83z54tAt8h2WRRG649I9sHOQgxg9cKRzd+HvSbyD+6ktrpKp5ldxwHEjb5v6yulHr3Gd6lah2qi7C4vvrTXWRruX73hyBgj29DcAKKcyzclQp4JinBynmvSNSgReW2oQHGBPbMN33ENQU8QNs0wwiGxoGYEc08pLrWe4OmihLy2XbVWZJH7Ca/39ItRkDhGgHjp26d2M3KZRTSJZROd333BrlA5pFWnpDSkkZocx7SHJz3DQGYIzssKBXyNUoc3zF4kB45qK4ZZZGE7GxDEvW97Kcy0Qu4CzkIFgBr55H/fozRYqczr17f5YNeY39OrkcOFa2i1bh9UVCyTHI6Szmak1ydopLY8oOjea7hqlAT6H6jFMAlGzLuPmtqN4vLafip9fz2fgMQ2hrxcmDKFBwkTy3lhMOKKPco4mHT7csSi8B7k/rZkujaHKWUvQjsB+uvndG9vJeiPIpw6k5qsUHW5caP4jZyWICZj7TVfrfRb5NwJ+vnopdkst6SbVPUsl99lx5HM4ryuy94=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
